#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#include "tusb_option.h"

#define CPU_MIMXRT1062DVJ6B 1

#define CFG_TUSB_MCU OPT_MCU_MIMXRT10XX
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUD_ENABLED 1
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 1
#define CFG_TUD_CDC_RX_BUFSIZE 256
#define CFG_TUD_CDC_TX_BUFSIZE 256
#define CFG_TUD_CDC_EP_BUFSIZE 64
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 0
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0
#define CFG_TUP_DCD_ENDPOINT_MAX 8
#define CFG_TUP_RHPORT0_MODE OPT_MODE_DEVICE
#define CFG_TUP_DCD_ENDPOINT_XFER_BUFFER_SIZE 256
#define CFG_TUP_USBIP_CHIPIDEA_HS 1

#endif /* _TUSB_CONFIG_H_ */
